# Allure report http://localhost:5050/allure-docker-service/projects/default/reports/latest/index.html

version: '3.9'

services:

  allure-unit:
    image: "frankescobar/allure-docker-service"
    container_name: allure-unit-tests
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
    ports:
      - "5050:5050"
    volumes:
      - ../../UnitTests/bin/Debug/net6.0/allure-results:/app/allure-results

  allure-integration:
    image: "frankescobar/allure-docker-service"
    container_name: allure-integration
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
    ports:
      - "5051:5050"
    volumes:
      - ../../IntegrationTests/bin/Debug/net6.0/allure-results:/app/allure-results

  allure-e2e:
    image: "frankescobar/allure-docker-service"
    container_name: allure-e2e
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 5
      KEEP_HISTORY: 1
    ports:
      - "5052:5050"
    volumes:
      - ../../E2ETest/bin/Debug/net6.0/allure-results:/app/allure-results